
# User/password credentials are stored in .env file
version: '3.8'

services:

  mongo:
    image: mongo:4.4.4

    container_name: smarter-backend-mongo

    expose:
      - 27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASS}
      MONGO_INITDB_DATABASE: 'smarter'
      MONGODB_SMARTER_USER: ${MONGODB_SMARTER_USER}
      MONGODB_SMARTER_PASS: ${MONGODB_SMARTER_PASS}

    # to export volume, as recommeded in https://registry.hub.docker.com/u/library/mysql/
    volumes:
      - type: bind
        source: ./mongodb-data
        target: /data/db

      - type: bind
        source: ./mongodb-home
        target: /home/mongodb

      - type: bind
        source: ./docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d

    networks:
      - smarter-backend

  uwsgi:
    # a custom image for flask
    build: ./uwsgi

    container_name: smarter-backend-uwsgi

    # You can pass multiple environment variables from an external file through
    # to a service’s containers with the ‘env_file’ option
    env_file:
      - .env

    # exec a different command from image
    command: uwsgi --ini /var/uwsgi/smarter_uwsgi.ini --memory-report

    # set working dir for uwsgi
    working_dir: /var/uwsgi/smarter/

    # define volumes
    volumes:
      - type: bind
        source: ./flask-data/
        target: /var/uwsgi/

    # Expose the default port

    # link container to database
    links:
      - mongo

    networks:
      - smarter-backend

  nginx:
    # a custom image for NGINX
    build: ./nginx

    container_name: smarter-backend-nginx

    volumes:
      - type: bind
        source: ./nginx/conf.d/
        target: /etc/nginx/conf.d/

      - type: bind
        source: ./flask-data/
        target: /var/uwsgi/

    ports:
      - "27080:80"

    # link container uwsgi
    links:
      - uwsgi

    networks:
      - smarter-backend


networks:
  smarter-backend:
