
# User/password credentials are stored in .env file
version: '3.8'

services:

  mongo:
    image: mongo:4.4

    expose:
      - 27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASS}
      MONGO_INITDB_DATABASE: 'smarter'
      HOME: /home/mongodb
      MONGODB_SMARTER_USER: ${MONGODB_SMARTER_USER}
      MONGODB_SMARTER_PASS: ${MONGODB_SMARTER_PASS}

    # The entrypoint of the image is created to pass its arguments along to mongod
    command: --wiredTigerCacheSizeGB 1

    # to export volume, as recommeded in https://registry.hub.docker.com/u/library/mysql/
    volumes:
      - type: bind
        source: ./mongodb-data
        target: /data/db

      - type: bind
        source: ./mongodb-home
        target: /home/mongodb

      - type: bind
        source: ./docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d

    networks:
      - default

  uwsgi:
    # a custom image for flask
    build:
      # required to include poetry stuff into uwsgi image
      context: .
      dockerfile: uwsgi/Dockerfile

    environment:
      PYTHONPATH: "/var/uwsgi/smarter/"

    # You can pass multiple environment variables from an external file through
    # to a service’s containers with the ‘env_file’ option
    env_file:
      - .env

    # exec a different command from image
    command: uwsgi --ini /var/uwsgi/smarter_uwsgi.ini --memory-report

    # set working dir for uwsgi
    working_dir: /var/uwsgi/smarter/

    # define volumes
    volumes:
      - type: bind
        source: ./flask-data/
        target: /var/uwsgi/

      # required by coveralls
      - type: bind
        source: ./.git/
        target: /var/uwsgi/smarter/.git/
        read_only: true

    # Expose the default port

    # link container to database
    links:
      - mongo

    networks:
      - default

  nginx:
    # a custom image for NGINX
    build: ./nginx

    volumes:
      - type: bind
        source: ./nginx/conf.d/
        target: /etc/nginx/conf.d/

      - type: bind
        source: ./flask-data/
        target: /var/uwsgi/

    ports:
      - "27080:80"

    # link container uwsgi
    links:
      - uwsgi

    networks:
      - default


networks:
  default:
